### ISSUE TITLE
How to plot

### ISSUE THREAD

**Issue by frchalaoux** [Becksteinlab/GromacsWrapper#105]
Hi All,

Have you a snippet that show me how to plot a simple xvg file with GromacsWrapper API ?

My first test with the API documentation stay quiet :

```python
import gromacs.fileformats.xvg as xvg
pot=xvg.XVG("potential.xvg")
pot.plot()
pot.plot(columns=[0,1])
```
FR.

**Comment by PicoCentauri** [comment]
Hey frchalaoux,

are you running in an _jupyter notebook_ or in an _ipython_ session? There you can try to add the magic command `%matplotlib inline`. 

Best

**Comment by orbeckst** [comment]
Either use the [%matplotlib](http://ipython.readthedocs.io/en/stable/interactive/plotting.html) magic command https://github.com/Becksteinlab/GromacsWrapper/issues/105#issuecomment-277552539 or explicitly request the figure: You might have to do a
```python
import matplotlib,pyplot as plt
plt.show()
```
or save the figure to a file
```
pot.figure.savefig("potential.png")
```

**Comment by frchalaoux** [comment]
Perfect guys, It works with both  ;-) 

I tested xmgrace these last months but was not very happy with certains capabilities. It helped me to convince with nice figures but now I have to automate all these things with matplotlib/Pandas, etc ... cause MD become my daily bread.

Thanks.
