### ISSUE TITLE
How to retrieve header information from xvg files

### ISSUE THREAD

**Issue by frchalaoux** [Becksteinlab/GromacsWrapper#107]
Hi,

I would like to plot with title, x and y units, etc ... (all this information is written in the xvg header). Is there a way to do it ?

**Comment by frchalaoux** [comment]
I did with an external function but as in #13 cause it seems it is not still implemented.

**Comment by orbeckst** [comment]
Please create a PR so that it can be reviewed.

**Comment by frchalaoux** [comment]
Ok, I will to switch from Mercurial to Git then I will create the PR.
