### ISSUE TITLE
gromacs.grompp output in my Jupyter nootbook

### ISSUE THREAD

**Issue by frchalaoux** [Becksteinlab/GromacsWrapper#108]
Hi all,

I use gromacswrapper 0.6.2. and gromacs 2016-1

Neither,
gromacs.grompp('v', f="ions.mdp", c="solvate_clean.gro", p="topol.top", o="ions.tpr")
or 
gromppy = Grompp(v=True, f="ions.mdp", c="solvate_clean.gro", p="topol.top", o="ions.tpr")
gromppy.run(v=True)

writes into the output of my Jupyter nootbook ('v', or v=True).

By cons, It writes in an ipython session.

Did I forgot something ?

FR.

**Comment by orbeckst** [comment]
Have a look at the options for `stdout` and `stderr`  under [Input/Output](http://gromacswrapper.readthedocs.io/en/latest/gromacs/core/core.html#input-output-label) – *maybe* that is going to help.

By default we do write to stderr and stdout (unless you changed some of the flags – [Input/Output](http://gromacswrapper.readthedocs.io/en/latest/gromacs/core/core.html#input-output-label)) so maybe the notebook is doing its own thing with these filedescriptors? – maybe http://stackoverflow.com/questions/35936086/jupyter-notebook-does-not-print-logs-to-the-output-cell ??

**Comment by frchalaoux** [comment]
Thanks, I will investigate these tracks but there is already a problem with the ipythonkernel=4.3.1.
To be continued ...
FR.

**Comment by orbeckst** [comment]
Closing, no further comments. Please re-open if necessary.
