### ISSUE TITLE
fix numkit float/int indexing

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/GromacsWrapper#115]
The following numkit tests in `test_integration.py` fail
* Test_simps_error.test_odd_const_x 
* Test_simps_error.test_odd_const_x_dx

The problem is in `numkit.integration.simps_error()`:
```
            if len(x.shape) == 1:
                shapex = numpy.ones(nd)
                shapex[axis] = x.shape[0]
                saveshape = x.shape
                returnshape = True
               x=x.reshape(tuple(shapex))

E               TypeError: 'numpy.float64' object cannot be interpreted as an index
```
The argument for reshap (`shapex`) must be an integer or tuple of integers. 

# Fix
Probably just
```python
                shapex = numpy.ones(nd, dtype=np.int_)
```

# Background
* see https://github.com/Becksteinlab/GromacsWrapper/pull/110#issuecomment-288475330 for initial discussion and e.g. https://travis-ci.org/Becksteinlab/GromacsWrapper/jobs/187547479 for failure in numkit `test_integration`
* see rbgirshick/py-faster-rcnn#481 for description: deprecated indexing with floats has been removed in numpy 1.12.

**Comment by dotsdl** [comment]
See #114.
