### ISSUE TITLE
From dev to dev-py3

### ISSUE THREAD

**Issue by frchalaoux** [Becksteinlab/GromacsWrapper#121]
[patchs.zip](https://github.com/Becksteinlab/GromacsWrapper/files/981638/patchs.zip)
Hi All,

I tested Py3 and dev version with gromacs 5.1.2 and Anaconda 3 but without success . So I decided to elucidate some of the errors of the dev (0.7.0) version with gromacs 5.1.2 and Anaconda 3. The result is attached to these 2 patchs. If you give the rights to push it directly in a repository I will do it. Let me know.

**Comment by orbeckst** [comment]
Hi @frchalaoux , python 3 patches are *very welcome* as the next goal is Py3 #44 – please submit a pull request and we start with reviewing the PR and once everything is good, we merge.

I am closing this issue and we continue the discussion at #44 .
