### ISSUE TITLE
sorry, how can I re-open an old issue?

### ISSUE THREAD

**Issue by lanselibai** [Becksteinlab/GromacsWrapper#126]
I try to open an old issue, but it seems that I do not have the authority. Sorry I post it here as well.

https://github.com/Becksteinlab/GromacsWrapper/issues/125

If I comment on an old issue, can @orbeckst  still see it?

-------------------------------
Hi @orbeckst , I am not sure if I did it correctly.

I used 
```
import gromacs.formats
xpm = gromacs.formats.XPM("./ss.xpm")
print xpm.array[0, 1]
```

So this should output the first time and the second residue. But what I got is `Coil` while it is `G` in the `ss.xpm` file, which should be `3-Helix`. The file is [here](https://github.com/lanselibai/attach/blob/master/ss.xpm)

**Comment by orbeckst** [comment]
I reopened #125 .

I also see comments on closed issues.
