### ISSUE TITLE
get_GMXRC fails on macOS with brew

### ISSUE THREAD

**Issue by richardjgowers** [Becksteinlab/GromacsWrapper#148]
So I'm trying out a "new user experience" and trying to install this from scratch.  So on MacOS there's no conda package for gromacs 2018, so I used brew.

I get this failure:
`    def test_set_gmxrc_environment():`

(gromacs) [~/code/GromacsWrapper]> which gmx
/usr/local/bin/gmx

Whereas my GMXRC is at:
/usr/local/share/GMXRC

It looks like the code looks in `GMXRC = os.path.join(bindir, 'GMXRC')`

I'm not entirely sure how installation "usually" works, but is it worth adding the `../share/` location too?

**Comment by orbeckst** [comment]
Btw, please just ping me if there's no reply in a day or two –  I only see issues when I check various GitHub dashboards and there's not always time in the day available for indulging in such activity.

**Comment by richardjgowers** [comment]
Yeah so maybe brew is wrong, but I do think we should cater for people that lazily install gromacs like me :) I'll do a fix

**Comment by orbeckst** [comment]
Just for anyone looking here: bioconda has macOS GROMACS packages for 2018, 2019, 2020, 2021 https://anaconda.org/bioconda/gromacs/files (although for serious work I'd still compile my own).

I am not sure if the issue with brew persists. I'll tentatively mark this as won't fix but if anyone still considers it a problem please add your voice here and we can reopen.
