### ISSUE TITLE
MissingSectionHeaderError:

### ISSUE THREAD

**Issue by poojitharamachandra** [Becksteinlab/GromacsWrapper#177]
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/poojitharamachandra/.gromacswrapper.cfg, line: 1
'404: Not Found\n'

this issue persists in both gromacswrapper 0.8.0 and 0.7.0

any idea why?

the file read is at /home/poojitharamachandra/.local/lib/python2.7/site-packages/gromacs/templates/gromacswrapper.cfg

i had earlier followed instructions on https://github.com/Becksteinlab/GromacsWrapper/issues/54#issuecomment-228919025 to get support for gromacs 4.6.x

but now i have re-installed both gromacs and gromacs wrapper , but still the error continues

**Comment by orbeckst** [comment]
Can you post the content of the file `/home/poojitharamachandra/.gromacswrapper.cfg` here?

**Comment by orbeckst** [comment]
Also, try removing `/home/poojitharamachandra/.gromacswrapper.cfg` - you should be able to just 
```
source GMXRC
```
(or whatever you normally do to work with Gromacs) and GromacsWrapper 0.8 should pick up everything automatically.

**Comment by orbeckst** [comment]
No more feedback.
