### ISSUE TITLE
how to handle interactive data analysis?

### ISSUE THREAD

**Issue by Wade2016** [Becksteinlab/GromacsWrapper#178]
Hi All,
I am trying to build an automated workflow of my MD project.
In the data processing steps, is there a way to handle interactive options? i.e., in the gromacs.energy() function, how to chose the energy groups?
I was using bash to automation similar procedure, it was quite easy by adding "EOF" or by directly attaching a separate file after the required commend and options. 
It would be great if gromacswrapper can also integrate this property in the framwork

Best,
Wade

**Comment by theavey** [comment]
Is this not what you're looking for?
https://gromacswrapper.readthedocs.io/en/latest/gromacs/init.html#simple-usage

**Comment by Wade2016** [comment]
Many thanks, it works perfectly now.
