### ISSUE TITLE
Bug in Python3 - Capture Output File

### ISSUE THREAD

**Issue by rochoa85** [Becksteinlab/GromacsWrapper#181]
Hi all

After using the package with python3.5, and activating the 'capture_output' variable to store the output in a file, I got an error about the use of the function 'file', which is not implemented in python3. To locally correct the error I had to modify the file:

~/.local/lib/python3.5/site-packages/gromacs/core.py

And change the only call to the 'file' function by the 'open' function. It is an easy bug to correct for future compatible versions with python3

Regards

**Comment by orbeckst** [comment]
@rochoa85 thanks for the report. If you want to submit a PR, I'll be happy to review and merge it.

**Comment by orbeckst** [comment]
P.S.: Sorry for the long time in replying... lot's of other things to do and GromacsWrapper is not a high priority project at the moment but I still consider it maintained.
