### ISSUE TITLE
func.func_name is not used in Python 3

### ISSUE THREAD

**Issue by PolyachenkoYA** [Becksteinlab/GromacsWrapper#183]
File `fileformats/xvg.py` has `func_name` which was replaced with `func.__name__` in python 3.0. 
I thought it would be safer to run 2to3 on all files so I ran 
`2to3 -w ./*` 
in `~/anaconda3/lib/python3.7/site-packages/gromacs` and it failed with 
`ImportError: cannot import name 'namedtuple' from 'collections' (/home/ypolyach/anaconda3/lib/python3.7/site-packages/gromacs/collections.py)`. Turns out python has [https://docs.python.org/3/library/collections.html](collections) so `2to3` fails to run in a directory which has a `collections.py` in it.
So, the **problem**: `2to3` must be run on some files in `gromacs/*` but it fails because of `collections.py` naming.

**Comment by orbeckst** [comment]
Why do you need to run 2to3? GW runs in Python 3 as well as in 2. Or do you have a particular issue with Python 3, i.e., does XVG fail in some way? If so, raise an issue for that specific bug, please.

**Comment by PolyachenkoYA** [comment]
I do have an issue with XVG, yes. As I wrote in the initial git-post, XVG
has func_name, but there is no such a thing in 3.0, but there is a
fun.__name__ instead.

**Comment by orbeckst** [comment]
Ok: need to change https://github.com/Becksteinlab/GromacsWrapper/blob/79e5594fd2af8e3f4c04f7d1af8b23bf93ccc113/gromacs/fileformats/xvg.py#L1084 to

```python
            try:
                funcname = func.func_name    # Python 2
            except AttributeError:
                funcname = func.__name__     # Python 3
            warnings.warn("Plot had %d datapoints > maxpoints = %d; decimated to %d regularly "
                          "spaced points from the histogrammed data with %s()."
                          % (ny, maxpoints, maxpoints, funcname),
                          category=AutoCorrectionWarning)
```

**Comment by PolyachenkoYA** [comment]
OK, thanks! done.
