### ISSUE TITLE
fileformats submodule missing?

### ISSUE THREAD

**Issue by richardjgowers** [Becksteinlab/GromacsWrapper#20]
I'm trying to read an ITP file, like here:

http://becksteinlab.github.io/GromacsWrapper/gromacs/core/fileformats/itp.html

And I get:

```
In [1]: import gromacs
In [2]: gromacs.fileformats
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-30aee3513de1> in <module>()
----> 1 gromacs.fileformats

AttributeError: 'module' object has no attribute 'fileformats'
```

**Comment by orbeckst** [comment]
Thanks for the PR & fix. Just be aware that reading of ITPs is fraught with difficulties, see most of the [issues tagged with fileformat](https://github.com/Becksteinlab/GromacsWrapper/labels/fileformats).
