### ISSUE TITLE
unit tests framework

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/GromacsWrapper#23]
Unit tests (with CI) would be great. Given that there are deb packages of Gromacs, one could test multiple versions of Gromacs (especially 4.6.x vs 5.0.x vs 5.1.x) but this is a lot of work at the moment.

**Comment by jandom** [comment]
Hi Oli, 

I'm working on this. The best set of tests+data files I found actually belongs to pandas - I'm inspired by their structure. It's much simpler than anything I've seen (especially the datafile linking...)

My main aim will be to:
- [ ] setup the testing boilerplate
- [ ] add tests for the TOP reader I contributed

**Comment by orbeckst** [comment]
When #34 is merged we will close this issue and then raise individual issues for the necessary tests.

**Comment by orbeckst** [comment]
#34 was merged... so we officially have a nucleus of tests. Thanks @jandom ... onwards and upwards.
