### ISSUE TITLE
Readthedocs hosting

### ISSUE THREAD

**Issue by MichalKononenko** [Becksteinlab/GromacsWrapper#24]
Why are we building docs in the repo when [readthedocs](https://readthedocs.org/) can host them for us?

**Comment by orbeckst** [comment]
Fair comment, although RTD didn't work nicely for me for a long time. If all looks ok with the current releases we can removed the built docs from the repository.

**Comment by orbeckst** [comment]
http://gromacswrapper.readthedocs.org/en/latest/ looks ok...

**Comment by orbeckst** [comment]
Closed with ef62459
