### ISSUE TITLE
docs incomplete on readthedocs

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/GromacsWrapper#32]
There are huge gaps in the autogenerated docs on http://gromacswrapper.readthedocs.org. Needs to be read, checked, and fixed.

Example: missing docs for most building block modules: http://gromacswrapper.readthedocs.org/en/latest/gromacs/building_blocks.html

**Comment by dotsdl** [comment]
We can use [conda](http://docs.readthedocs.org/en/latest/conda.html) to build environment on readthedocs now. We use this for [MDSynthesis](http://mdsynthesis.readthedocs.org/) and it works quite well. Happy to set this up.

There are conda gromacs builds from acellera we can use to grab a recent gromacs to build classes against: https://anaconda.org/acellera

**Comment by orbeckst** [comment]
Please try it!

**Comment by dotsdl** [comment]
Okay, we have docs that build the environment, including gromacs 5.1, using conda: https://readthedocs.org/projects/mdsynthesis/builds/3881150/

But, when building the class docs for the building blocks, we get errors because the config we ship with is for gromacs 4.x, and so things like ``grompp`` can't be found. Quick and dirty solution is to replace current [gromacswrapper.cfg](https://github.com/Becksteinlab/GromacsWrapper/blob/develop/gromacs/templates/gromacswrapper.cfg) with one that works with 5.x names. Longer-term solution is #49.

We cannot install a gromacs 4.x version on readthedocs with conda because there are are no 4.x packages available on the anaconda cloud. If we want this, we'd have to build our own first.

**Comment by orbeckst** [comment]
> 
> We cannot install a gromacs 4.x version on readthedocs with conda because there are are no 4.x packages available on the anaconda cloud. If we want this, we’d have to build our own first.

There are Ubuntu packages that we can use for 4.x … probably in parallel to condo packages.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by dotsdl** [comment]
@orbeckst how would we do this under readthedocs? We can't use ``apt`` to build the environment on readthedocs.

**Comment by orbeckst** [comment]
> On 13 Apr, 2016, at 16:06, David Dotson <notifications@github.com> wrote:
> 
> @orbeckst how would we do this under readthedocs? We can’t use apt to build the environment on readthedocs.

You’re right, of course. I was thinking about Travis… 

If we can have 5.x on RTD then perhaps we should just ship with 5.x cfg.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by dotsdl** [comment]
I'll change the existing config to work for gromacs 5.x on the development branch, then. If #49 gets done soonish, then we can support gromacs 4.x out of the box, too.

**Comment by orbeckst** [comment]
On 13 Apr, 2016, at 22:34, David Dotson wrote:

> I'll change the existing config to work for gromacs 5.x on the development branch, then. If #49 gets done soonish, then we can support gromacs 4.x out of the box, too.

Sounds good.

**Comment by dotsdl** [comment]
So, things are looking better (gromacs tools like like they're being found), but we're still getting some failures. Have a look at the output of the sphinx invocation. I'm not sure what's going on here with just a quick glance: https://readthedocs.org/projects/gromacswrapper/builds/3927393/

**Comment by orbeckst** [comment]
Not really sure, I find sphinx output difficult to digest. I need to look at it locally.

Just as a note on what needs fixing:

[gromacs – GromacsWrapper Package Overview](http://gromacswrapper.readthedocs.org/en/develop/gromacs/init.html) has dead links to
* gromacs.formats
* gromacs.setup

even though [gromacs.formats](http://gromacswrapper.readthedocs.org/en/develop/gromacs/core/formats.html) exists. I can't find `gromacs.setup` anywhere.

**Comment by orbeckst** [comment]
The docs build locally with sphinx. I will close this issue if they build on RTD.

**Comment by orbeckst** [comment]
Everything builds on RTD. Minor doc things will be corrected in 0.5.1.
