### ISSUE TITLE
set up CI

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/GromacsWrapper#39]
Once we have a tests infrastructure in place #23, we need
- [x] Travis CI
- [x] coverage
- [x] add test and coverage badges to README

**Comment by orbeckst** [comment]
For most of the tests we need to install Gromacs as well. This *should* be possible through `aptitude` on the containerized Travis infrastructure.

* Gromacs 4.6.5 is available as [trusty (14.04 LTS): gromacs (4.6.5-1build1) [universe]](http://packages.ubuntu.com/trusty/gromacs)
* Gromacs 5.0.x: [wily: gromacs (5.0.6-1) [universe] ](http://packages.ubuntu.com/source/wily/gromacs)
* Gromacs 5.1.x: [Xenial: gromacs (5.1.2-1ubuntu1) [universe]](http://packages.ubuntu.com/source/xenial/gromacs)

I don't know if it's possible to pull in newer packages into a 14.04 machine. Gromacs 4.6.5 will be easy, all the other... we will see. It would be great, though, to have a test matrix with different Gromacs installations.

**Comment by dotsdl** [comment]
We can use conda. There are builds provided by acellera: https://anaconda.org/acellera/gromacs

**Comment by orbeckst** [comment]
@dotsdl can you add the travis stuff from MDPOW? This seems to be *almost* working.

**Comment by dotsdl** [comment]
Yes. I'll convene with @ianmkenney and we'll slay this one.

**Comment by dotsdl** [comment]
We now have working CI, but some of the tests are failing. Haven't dug into fixing these yet; check the test output for starting points: https://travis-ci.org/Becksteinlab/GromacsWrapper

Coverage reads at 88%. Not bad, but I guess we cheat a bit since we generate many classes dynamically.

**Comment by orbeckst** [comment]
@dotsdl : I don't see the coverage at https://codecov.io/gh/Becksteinlab/GromacsWrapper — is this because `codecov` is only ran when the tests pass?

And the [output from travis](https://travis-ci.org/Becksteinlab/GromacsWrapper#L343) seems to indicate that the 88% coverage are the coverage *in the test files*, not in the code itself.

I added the badges to the README but until coverage shows up in codecov I will leave this issue open.

**Comment by dotsdl** [comment]
@orbeckst ah sorry, didn't look closely enough at what was included in coverage. I'll fix this.

**Comment by dotsdl** [comment]
K...now with better accounting, coverage looks like about 30%. I think codecov doesn't pick up failed builds, either, so we have to get these passing before that is fixed, too.

**Comment by orbeckst** [comment]
I can close this issue when I get coverage on travis but for this to happen, all current tests must pass, i.e., #61 must be fixed.

**Comment by orbeckst** [comment]
@ianmkenney got Gromacs working with PR Becksteinlab/MDPOW#44 (see Becksteinlab/MDPOW#41).

**Comment by orbeckst** [comment]
Tests passing and coverage properly reported.
