### ISSUE TITLE
remove gridmatmd

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/GromacsWrapper#41]
`gridmatmd.pl` does not seem to be used (at least through GW) and there are better tools available. It currently breaks `sudo pip install` #40 and it's an ugly hack... so let's get rid of it.

- [ ] remove gridmatmd.pl
- [ ] remove from template config file
- [ ] remove ~~from tools~~ `analysis/plugins/gridmatmd.py`
- [ ] remove from docs

**Comment by frchalaoux** [comment]
Hi,

Ok for gridmatmd.pl, I suppose you think about /site/tl/home/fchalaoux 
/GromacsWrapper-develop/gromacs/external/GridMAT-MD_v1.0.2/GridMAT-MD.pl ?

But for the others, where are the paths of these objects in the distribution  to remove ?

FR.

**Comment by orbeckst** [comment]
The list just says that gridmatmd shows up in various parts of the code. Probably the best way to find them is to run
```
git grep GridMAT-MD
```

It turns out that it's not in tools but in `analysis/plugins/gridmatmd.py`... so it should be easy to remove.

**Comment by orbeckst** [comment]
If you want to do this, I'd be more than happy if you send a pull request.

**Comment by orbeckst** [comment]
@frchalaoux can you check that installation is working now?

**Comment by frchalaoux** [comment]
OK,but how to clean properly my previous install with python setup.py install ?

**Comment by orbeckst** [comment]
On 7 Apr, 2016, at 05:59, frchalaoux wrote:

> OK,but how to clean properly my previous install with python setup.py install ?


Find out where it was installed (eg in ipython

       import gromacs
       gromacs??

and look at the filename.

Then 

   rm -r /path/to/gromacswrapper

If you can't find out where it is installed, just install again in the same way as before and note the path. Paste the output.

There might also be some other files where the path is being entered. Possibly @dotsdl can contribute some quick answers.
