### ISSUE TITLE
GridMAT-MD problem

### ISSUE THREAD

**Issue by frchalaoux** [Becksteinlab/GromacsWrapper#43]
Hi,

When I start an import of gromacs in my python interpreter I obtain this message.
What do I need to correct in my system ?

FR.
[fchalaoux@frtow0216 Lysozyme2]$ python
Python 2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import gromacs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/gromacs/__init__.py", line 199, in <module>
  File "build/bdist.linux-x86_64/egg/gromacs/config.py", line 658, in <module>
  File "/site/tl/work/users/fchalaoux/Computing/anaconda25/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1150, in resource_filename
  File "/site/tl/work/users/fchalaoux/Computing/anaconda25/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1862, in get_resource_filename
  File "/site/tl/work/users/fchalaoux/Computing/anaconda25/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1883, in _extract_resource
KeyError: 'gromacs/external/GridMAT-MD_v1.0.2/GridMAT-MD.pl'

**Comment by frchalaoux** [comment]
Should I have to apply https://github.com/Becksteinlab/GromacsWrapper/issues/41 
before build GW ?

FR.

**Comment by orbeckst** [comment]
I think it would help if #41 was solved.

How did you install GromacsWrapper? I am not sure why it seems to run from the build directory? Are you running python from inside the GW sources? (What does `pwd` say?)

**Comment by frchalaoux** [comment]
Hi,
I installed GW with python setup.py build, then python setup.py install
I'm running python and import gromacs from outside GW.

**Comment by orbeckst** [comment]
Can you check that installation is working, now that #41 has been completed?

**Comment by frchalaoux** [comment]
Better with the last https://github.com/Becksteinlab/GromacsWrapper.git with your clean of GridMAT-MD. But even beeing outside GromacsWrapper install folder and having sourced GMRC; change my .gromacswrapper.cfg for grompp to gmx:grompp or gmx_mpi:grompp or gmx_mpi:Grompp ,  I got always the following problem. 

[fchalaoux@frtow0216 ~]$ python
Python 2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import gromacs
/site/tl/work/users/fchalaoux/Computing/anaconda25/lib/python2.7/site-packages/GromacsWrapper-0.4.1.dev0-py2.7.egg/gromacs/__init__.py:274: GromacsImportWarning: Some Gromacs commands were NOT found; maybe source GMXRC first? The following are missing:
['a_gridcalc', 'a_ri3dc', 'demux_pl', 'do_dssp', 'editconf', 'eneconv', 'g_anadock', 'g_anaeig', 'g_analyze', 'g_angle', 'g_bar', 'g_bond', 'g_bundle', 'g_chi', 'g_cluster', 'g_clustsize', 'g_confrms', 'g_count', 'g_covar', 'g_current', 'g_density', 'g_densmap', 'g_dielectric', 'g_dih', 'g_dipoles', 'g_disre', 'g_dist', 'g_dyndom', 'g_enemat', 'g_energy', 'g_filter', 'g_flux', 'g_gyrate', 'g_h2order', 'g_hbond', 'g_helix', 'g_helixorient', 'g_kinetics', 'g_lie', 'g_luck', 'g_mdmat', 'g_membed', 'g_mindist', 'g_morph', 'g_msd', 'g_nmeig', 'g_nmens', 'g_nmtraj', 'g_order', 'g_pme_error', 'g_polystat', 'g_potential', 'g_principal', 'g_protonate', 'g_rama', 'g_rdf', 'g_ri3dc', 'g_rms', 'g_rmsdist', 'g_rmsf', 'g_rotacf', 'g_rotmat', 'g_saltbr', 'g_sas', 'g_select', 'g_sgangle', 'g_sham', 'g_sigeps', 'g_sorient', 'g_spatial', 'g_spol', 'g_tcaf', 'g_traj', 'g_tune_pme', 'g_vanhove', 'g_velacc', 'g_wham', 'g_wheel', 'g_x2top', 'genbox', 'genconf', 'genion', 'genrestr', 'gmxcheck', 'gmxdump', 'grompp', 'make_edi', 'make_ndx', 'mdrun', 'mdrun_d', 'mk_angndx', 'pdb2gmx', 'tpbconv', 'trjcat', 'trjconv', 'trjorder', 'xplor2gmx_pl', 'xpm2ps']

/site/tl/work/users/fchalaoux/Computing/anaconda25/lib/python2.7/site-packages/GromacsWrapper-0.4.1.dev0-py2.7.egg/gromacs/cbook.py:205: GromacsImportWarning: Failed to define a number of commands in gromacs.cbook. Most likely the Gromacs installation cannot be found --- source GMXRC!
/site/tl/work/users/fchalaoux/Computing/anaconda25/lib/python2.7/site-packages/GromacsWrapper-0.4.1.dev0-py2.7.egg/gromacs/__init__.py:288: GromacsImportWarning: Some Gromacs commands were NOT found when importing gromacs.cbook:
Failed to find Gromacs command 'grompp', maybe its not on PATH or GMXRC must be sourced?

**Comment by orbeckst** [comment]
Please post 

1. your .gromacswrapper.cfg
2. `source GMXRC` and output of `which grompp`

**Comment by orbeckst** [comment]
I am closing this issue (the GridmatMD problem seems to be solved) and we continue the discussion at #42 --- please post your cfg and path info there.
