### ISSUE TITLE
Allow use of Gromacs 5.1.x gmx_mpi command instead of gmx

### ISSUE THREAD

**Issue by frchalaoux** [Becksteinlab/GromacsWrapper#48]
My IT created a command gmx_mpi to contrast with a simple Gromacs installation.
But I can create an UNIX alias (alias gmx=gmx_mpi) to get around the problem !? My Gromacs command seems to work but for GW it not may be sufficient ?
So, may be It could be possible to allow GW use internally of Gromacs 5.1.x gmx_mpi command instead of gmx

**Comment by frchalaoux** [comment]
My gromacs at work is 5.0.4.

**Comment by orbeckst** [comment]
@frchalaoux thanks for opening this issue as a follow-up to #42.

Just creating a shell alias will not be enough. However, as a quick work-around you could ask them to install a *symbolic link*:
```
ln -s gmx_mpi gmx
```

Of course, we also want to fix this within GromacsWrapper. What do you (and perhaps @whitead ) think of the idea to interpret
```
gmx_mpi:mdrun gmx:grompp
```
in the cfg file to mean that GW should really call `gmx_mpi mdrun ...` and `gmx grompp`? This would probably be the most intuitive for the user and also provide maximum flexibility for people who often have mixed serial/threaded and mpi installations.

**Comment by frchalaoux** [comment]
And how will react GW  with in the same cfg file, gmx_mpi:mdrun gmx:grompp gmx:mdrun ?

**Comment by orbeckst** [comment]
I'll leave this issue open until we have a solution --- maybe #49 --- but it's not solved yet.

> And how will react GW with in the same cfg file, gmx_mpi:mdrun gmx:grompp gmx:mdrun ?

There needs to be sufficient flexibility so that a user can adapt it to their environment. I typically have serial and mpi versions in the same path (basically, same GMXRC) so I would want to have both `gmx_mpi mdrun` and `gmx mdrun` available. But this might be very different for others.

**Comment by frchalaoux** [comment]
The tip "ln -s gmx_mpi gmx seems to work. It stay one problem with the _mindist_ command (see below). In my .gromacswrapper.cfg you can read that  _gmx:mindist_ is present. Trust me !
I don't know why, any idea ?

Cheers, FR.

In [1]: import gromacs
/site/tl/work/users/fchalaoux/Computing/anaconda25/lib/python2.7/site-packages/GromacsWrapper-0.4.1.dev0-py2.7.egg/gromacs/__init__.py:274: GromacsImportWarning: Some Gromacs commands were NOT found; maybe source GMXRC first? The following are missing:                                                                                                      
['g_mindist']

**Comment by orbeckst** [comment]
I think `mindist` does not exist in Gromacs 5.x any more. *Remove it from your .gromacswrapper.cfg*.

**Comment by frchalaoux** [comment]
What do you think of that ?

FR

[fchalaoux@frtow0216 ~]$ gmx_mpi mindist -h
GROMACS:    gmx mindist, VERSION 5.0.4     

GROMACS is written by:
Emile Apol         Rossen Apostolov   Herman J.C. Berendsen Par Bjelkmar       
Aldert van Buuren  Rudi van Drunen    Anton Feenstra     Sebastian Fritsch     
Gerrit Groenhof    Christoph Junghans Peter Kasson       Carsten Kutzner       
Per Larsson        Justin A. Lemkul   Magnus Lundborg    Pieter Meulenhoff     
Erik Marklund      Teemu Murtola      Szilard Pall       Sander Pronk          
Roland Schulz      Alexey Shvetsov    Michael Shirts     Alfons Sijbers        
Peter Tieleman     Christian Wennberg Maarten Wolf                             
and the project leaders:                                                       
Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel                 

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2014, The GROMACS development team at          
Uppsala University, Stockholm University and                      
the Royal Institute of Technology, Sweden.                        
check out http://www.gromacs.org for more information.            

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License          
as published by the Free Software Foundation; either version 2.1  
of the License, or (at your option) any later version.            

GROMACS:      gmx mindist, VERSION 5.0.4
Executable:   /site/tl/app/x86_64/discovery/academic/gromacs/5.0.4/icc-2015_mkl_openmpi-1.8.5_plumed-2.1.3-sp/bin/gmx_mpi
Library dir:  /site/tl/app/x86_64/discovery/academic/gromacs/5.0.4/icc-2015_mkl_openmpi-1.8.5_plumed-2.1.3-sp/share/gromacs/top
Command line:                                                                                                                  
  gmx_mpi mindist -h                                                                                                           

SYNOPSIS

gmx mindist [-f [<.xtc/.trr/...>]] [-s [<.tpr/.tpb/...>]] [-n [<.ndx>]]
            [-od [<.xvg>]] [-on [<.xvg>]] [-o [<.out>]]                
            [-ox [<.xtc/.trr/...>]] [-or [<.xvg>]] [-nice <int>] [-b <time>]
            [-e <time>] [-dt <time>] [-tu <enum>] [-[no]w] [-xvg <enum>]    
            [-[no]matrix] [-[no]max] [-d <real>] [-[no]group] [-[no]pi]     
            [-[no]split] [-ng <int>] [-[no]pbc] [-[no]respertime]           
            [-[no]printresname]                                             

DESCRIPTION

gmx mindist computes the distance between one group and a number of other
groups. Both the minimum distance (between any pair of atoms from the    
respective groups) and the number of contacts within a given distance are
written to two separate output files. With the -group option a contact of an
atom in another group with multiple atoms in the first group is counted as one
contact instead of as multiple contacts. With -or, minimum distances to each
residue in the first group are determined and plotted as a function of residue
number.

With option -pi the minimum distance of a group to its periodic image is
plotted. This is useful for checking if a protein has seen its periodic image
during a simulation. Only one shift in each direction is considered, giving a
total of 26 shifts. It also plots the maximum distance within the group and
the lengths of the three box vectors.

Also gmx distance calculates distances.

OPTIONS

Options to specify input and output files:

 -f     [<.xtc/.trr/...>] (traj.xtc) (Input)
     Trajectory: xtc trr cpt trj gro g96 pdb tng
 -s     [<.tpr/.tpb/...>] (topol.tpr) (Input, Opt.)
     Structure+mass(db): tpr tpb tpa gro g96 pdb brk ent
 -n     [<.ndx>] (index.ndx) (Input, Opt.) Index file
 -od    [<.xvg>] (mindist.xvg) (Output) xvgr/xmgr file
 -on    [<.xvg>] (numcont.xvg) (Output, Opt.) xvgr/xmgr file
 -o     [<.out>] (atm-pair.out) (Output, Opt.) Generic output file
 -ox    [<.xtc/.trr/...>] (mindist.xtc) (Output, Opt.)
     Trajectory: xtc trr trj gro g96 pdb tng
 -or    [<.xvg>] (mindistres.xvg) (Output, Opt.) xvgr/xmgr file

Other options:

 -nice  <int>    (19)       Set the nicelevel
 -b     <time>   (0)        First frame (ps) to read from trajectory
 -e     <time>   (0)        Last frame (ps) to read from trajectory
 -dt    <time>   (0)        Only use frame when t MOD dt = first time (ps)
 -tu    <enum>   (ps)       Time unit: fs, ps, ns, us, ms, s
 -[no]w          (no)       View output .xvg, .xpm, .eps and .pdb files
 -xvg   <enum>   (xmgrace)  xvg plot formatting: xmgrace, xmgr, none
 -[no]matrix     (no)       Calculate half a matrix of group-group distances
 -[no]max        (no)       Calculate *maximum* distance instead of minimum
 -d     <real>   (0.6)      Distance for contacts
 -[no]group      (no)
     Count contacts with multiple atoms in the first group as one
 -[no]pi         (no)       Calculate minimum distance with periodic images
 -[no]split      (no)       Split graph where time is zero
 -ng    <int>    (1)
     Number of secondary groups to compute distance to a central group
 -[no]pbc        (yes)      Take periodic boundary conditions into account
 -[no]respertime (no)
     When writing per-residue distances, write distance for each time point
 -[no]printresname (no)     Write residue names


gcq#240: "(That makes 100 errors; please try again.)" (TeX)

**Comment by orbeckst** [comment]
Ok, you proved me wrong. ;-)

Not sure what's going on. I'll need to take a closer look. 

--
Oliver Beckstein
email: orbeckst@gmail.com


Am May 12, 2016 um 2:32 schrieb François-Régis Chalaoux <notifications@github.com>:

> What do you think of that ?
> 
> FR
> 
> [fchalaoux@frtow0216 ~]$ gmx_mpi mindist -h
> GROMACS: gmx mindist, VERSION 5.0.4

**Comment by orbeckst** [comment]
Closed with PR #57.

**Comment by orbeckst** [comment]
(@whitead I assigned you to the issue post-closing because you actually solved it.)

**Comment by orbeckst** [comment]
@frchalaoux if the problem with `gmx_mpi mindist` persists even with the new GW 0.5.0 then please open a new issue specifically for it. Thanks!
