### ISSUE TITLE
Using interactive Gromacs commands

### ISSUE THREAD

**Issue by lrohrwasser** [Becksteinlab/GromacsWrapper#50]
Dear all, 
i have a very basic question concerning gromacs' interactive commands, as I would like to run the commands automatically.
There is a description in the gromacs documentation for the problem: http://www.gromacs.org/Documentation/How-tos/Using_Commands_in_Scripts
So now I wonder if there is also an easy way that GromacsWrapper can handle interactive commands?

Thanks a lot in advance,
Lisa

**Comment by orbeckst** [comment]
Going with the example,
```
echo 3 3 | g_rms -flags -s system.tpr -f md.xtc
```

would be in GW (e.g. inside `ipython` or the `python` interpreter)
```python
gromacs.g_rms(f="system.tpr", f="md.xtc", input=['3', '3'])
```

**Comment by orbeckst** [comment]
See also in docs under [Simple Usage](http://gromacswrapper.readthedocs.org/en/develop/gromacs/init.html#simple-usage).

**Comment by orbeckst** [comment]
Did this answer help? If yes, I can close the issue, otherwise I can try to help further.

**Comment by lrohrwasser** [comment]
Yes, thanks a lot! It helped ;-)
