### ISSUE TITLE
Failure loading file formats module using gromacs 5.1.1

### ISSUE THREAD

**Issue by scbarton** [Becksteinlab/GromacsWrapper#51]
I applied the fix described in [Issue 42](https://github.com/Becksteinlab/GromacsWrapper/issues/42) to enable use of GW with gromacs 5.1.1. However this change prevented the loading of some modules. For example the command `import gromacs.fileformats as f` returned this error:
```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-3a13da2817bc> in <module>()
----> 1 import gromacs.fileformats as f
/Users/scott/Library/Python/2.7/lib/python/site-packages/gromacs/__init__.py in <module>()
    184 __all__ = ['config', 'tools', 'cbook', 'fileformats']
    185 
--> 186 from . import fileformats
    187 
    188 # Note: analysis not imported by default (requires additional pre-requisites)
ImportError: cannot import name file formats
```

Fortunately I can remove the fix and successfully import `fileformats`, but I'd like to use both `fileformats` and `grompp` together. Any suggestions?

**Comment by orbeckst** [comment]
@scbarton , sorry for the delay in responding, been busy.
I am a bit puzzled by the error message because from it I cannot discern why changing the cfg file would lead to such an import error. I also have no idea why Python says "cannot import name file formats" (space between "file" and "formats").

Could you post your version of the cfg file? I can then try it locally and see if I can reproduce the error.

**Comment by scbarton** [comment]
Here's my [config file](https://github.com/Becksteinlab/GromacsWrapper/files/228042/gromacswrapper.cfg.txt), copied directly from [Issue 42](https://github.com/Becksteinlab/GromacsWrapper/issues/42)

Below I attempt to import gromacs twice, with different errors each time. The fileformats error is in the second attempt, it may be a namespace issue due to the second import.

```
In [1]:   import gromacs
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-8e7a136db98e> in <module>()
----> 1 import gromacs

/Users/scott/Library/Python/2.7/lib/python/site-packages/gromacs/__init__.py in <module>()
    283 # instances in the top level name space
    284 try:
--> 285     from . import cbook
    286 except OSError, err:
    287     warnings.warn("Some Gromacs commands were NOT found when importing gromacs.cbook:\n"+str(err),

/Users/scott/Library/Python/2.7/lib/python/site-packages/gromacs/cbook.py in <module>()
    199 
    200 try:
--> 201     _define_canned_commands()
    202 except (OSError, ImportError, GromacsError):
    203     warnings.warn("Failed to define a number of commands in gromacs.cbook. Most likely the "

/Users/scott/Library/Python/2.7/lib/python/site-packages/gromacs/cbook.py in _define_canned_commands()
    164 Writes a compact representation of the system centered on the protein""")
    165 
--> 166     rmsd_backbone = tools.G_rms(what='rmsd', fit='rot+trans',
    167                                 input=('Backbone','Backbone'),
    168                                 doc="""

AttributeError: 'module' object has no attribute 'G_rms'

In [2]:   import gromacs
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-8e7a136db98e> in <module>()
----> 1 import gromacs

/Users/scott/Library/Python/2.7/lib/python/site-packages/gromacs/__init__.py in <module>()
    184 __all__ = ['config', 'tools', 'cbook', 'fileformats']
    185 
--> 186 from . import fileformats
    187 
    188 # Note: analysis not imported by default (requires additional pre-requisites)

ImportError: cannot import name fileformats
```

**Comment by dotsdl** [comment]
@scbarton can you try out my [``gromacswrapper.cfg``](https://github.com/Becksteinlab/GromacsWrapper/issues/42#issuecomment-212539517)? We're in the process of revamping the config format ( #49 ), but until then this is all a bit hacky.

**Comment by dotsdl** [comment]
Note that I'm also using the ``develop`` branch of GromacsWrapper at the moment, and I know that the current release fails with this config due to the presence of the GridMatMD stuff ( #41 ) that was recently removed.

**Comment by orbeckst** [comment]
The problem appears to be that the import of cbook is not failing gracefully when some tools are not present and then stuff fails down the road.

1. Do you find the Gromacs tools in the shell, i.e. `which gmx` gives you something?
2. Are you using the latest develop branch that includes @whitead 's compatibility fix #46 ?

**Comment by scbarton** [comment]
With the `gromacswrapper.cfg` from @dotsdl and the dev branch, I was able to import gromacs including `gromacs.fileformats`. Thanks!  I did get this warning message though:
```
/Users/scott/Library/Python/2.7/lib/python/site-packages/gromacs/__init__.py:274: GromacsImportWarning: Some Gromacs commands were NOT found; maybe source GMXRC first? The following are missing:
['g_mindist']

  category=GromacsImportWarning)
```

**Comment by orbeckst** [comment]
Glad that this is working. 

Is there a gmx:mindist in the cfg file? If so you can remove it. 

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Apr 21, 2016 um 5:04 schrieb scbarton <notifications@github.com>:
