### ISSUE TITLE
Working with Gromacs 4.x

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/GromacsWrapper#54]
The default configuration file assumes Gromacs 5.x (see PR #53). If you want to use Gromacs 4.x you need a different config file such as the [previous version of gromacswrapper.cfg](https://github.com/Becksteinlab/GromacsWrapper/blob/e18d26038858a433d0e6318f4375d19d8b21858f/gromacs/templates/gromacswrapper.cfg).

With #49 we should get a mechanism to easily switch between versions.

**Comment by orbeckst** [comment]
I added a 4.6.5 cfg file as [gromacs/templates/gromacswrapper_465.cfg](https://github.com/Becksteinlab/GromacsWrapper/blob/develop/gromacs/templates/gromacswrapper_465.cfg) in c694d5c1151a0ffbb5a0ec6f506d0299ce948524.

**Comment by orbeckst** [comment]
If you want to quickly "install" the [gromacswrapper_465.cfg](https://github.com/Becksteinlab/GromacsWrapper/blob/develop/gromacs/templates/gromacswrapper_465.cfg) as `~/.gromacswrapper.cfg` use
```
curl https://raw.githubusercontent.com/Becksteinlab/GromacsWrapper/develop/gromacs/templates/gromacswrapper_465.cfg -o ~/.gromacswrapper.cfg
```

(Note: overwrites any existing `~/.gromacswrapper.cfg` file!)

**Comment by pslacerda** [comment]
If we put everything at config module inside functions can we just reload calling, lets say, `load_setup('~/.alternative_configuration.cfg')`?

**Comment by orbeckst** [comment]
That would be useful.

**Comment by orbeckst** [comment]
Note that with #68 solved you can just leave the whole `[gromacs]` section *empty* and load whichever Gromacs you like into your environment. GW will pick up all the standard tools.

**Comment by orbeckst** [comment]
Moving to a later milestone because the simplest solution is to not put any specific gromacs information into the cfg file and just source the Gromacs environment that you want manually and then let autoloading do its magic.

**Comment by orbeckst** [comment]
@pslacerda – autoloading works so well, maybe instead of reloading the whole config file we could clean the environment of GW (new `purge_environment()` function?) and then reload via the GMX file mechanism. (This probably mostly works already even without purging because envvars will just be overwritten. But I haven't tested it.)

In 0.6.x we are also honoring the *release* (although that is not working with Gromacs 2016 #96) and use it to try Gromacs 5 or 4. 

Originally, this issue aimed at a making different subsections in the config file where users could define different sets of commands to go with a release. But I think for all practical cases, autoloading from the ennvironment can do this.

It might be convenient to be able to select between different GMXRC files but if this is desired then I would have another issue opened.

I think as far as supporting Gromacs 5 *and* 4 goes, we now do this reasonably well and I close the issue. Feel free to re-open if you feel strongly about it.
