### ISSUE TITLE
Gromacs 5 does not use the genbox command

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/GromacsWrapper#62]
I found that gromacs.setup.solvate() calls genbox, which is no longer a valid gromacs command. This causes errors when using Gromacs 5.x.

**Comment by orbeckst** [comment]
I think `gmx solvate` is completely equivalent.

GW should define an alias... will raise an issue there.

**Comment by orbeckst** [comment]
closed in ef66d3e

**Comment by orbeckst** [comment]
(`gmx solvate` is not *completely equivalent* because it misses the `-ci` insertion option... but the aliases are a bit fragile anyway so I think the alias will solve 95% of the problems.)
