### ISSUE TITLE
Gromacs 5.x MDrunner class implementation incompatibilities

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/GromacsWrapper#64]
I have found two errors in regards to the MDrunner class and the `check_mdrun_success` function found in `run.py`.

1. Command passed to subprocess in the class method `run` does not include `gmx`, resulting in an `OSError`
2. `check_mdrun_success` searches the last couple of lines of the log file for the string `"Finished mdrun on node"` at the start of the line, while a successful run writes `"Finished mdrun on rank"`

My temporary fixes to these were as follows:
1. 
```python
cmd = self.commandline(**mpiargs) 
cmd = ['gmx'] + cmd
```
But this is clearly a sloppy solution while breaking Gromacs 4.x usage
2. Simply change `if line.startswith("Finished mdrun on node")` to `if line.startswith("Finished mdrun on rank")`

**Comment by orbeckst** [comment]
working on a fix... just needs testing

**Comment by orbeckst** [comment]
I added a test and it looks ok to me. I will merge #67 and then do a 0.5.1 releases as discussed in #70.
