### ISSUE TITLE
new Gromacs release numbering

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/GromacsWrapper#72]
From the [next Gromacs release onwards](http://manual.gromacs.org/documentation/2016-rc1/ReleaseNotes/index.html#highlights), Gromacs release numbers will look like **GROMACS 2016** or **GROMACS 2016.1**.

Sigh.

We'll have to deal with this eventually, and there's already a bit of discussion under PR #69  and it's also important for the cfg file #49.

**Comment by pslacerda** [comment]
I see no need to deal with this specifically as no code uses the release number. Except the PR #69, but doesn't matter either.

**Comment by orbeckst** [comment]
Yes, you're right, but I wanted it as a reminder.

**Comment by orbeckst** [comment]
Added "wontfix"... at least for the moment.
