### ISSUE TITLE
Improve loading times

### ISSUE THREAD

**Issue by pslacerda** [Becksteinlab/GromacsWrapper#75]
Importing GromacsWrapper take seconds. Most of time was wasted in extracting the help for docstrings. Seems that both running the help commands and communicating to acquire the text takes almost 90% of loading times.

This screenshot was taken while [profiling](https://julien.danjou.info/blog/2015/guide-to-python-profiling-cprofile-concrete-case-carbonara) the `gromacs` package importing:

![callgraph](https://cloud.githubusercontent.com/assets/149358/16899430/e98c383a-4bd9-11e6-97fe-cc97083538a5.png)

Albeit it is useful, isn't a such important feature and the library keeps running without it. Or maybe we can load it dynamically and make something similar to this:

```python
class GromacsCommand(Command):
    @property
    def __doc__(self):
        if not self.__doc_cache:
            # load docstring
        return self.__doc_cache
```

Another option would be to reset `GromacsCommand.__doc__` for each subclass. Now we can't simply set `Trjconv.__doc__ = "docstring"` because `Command` is an old style class (eg `class C(object): pass`) which disallow change members of `object` (ie `__doc__`). This change would allow it:

```python
# doesn't inherit from object
class Command:
    pass
```

**Comment by orbeckst** [comment]
I like the idea of loading the doc strings lazily!

**Comment by pslacerda** [comment]
Done =)
