### ISSUE TITLE
install Gromacs in Travis CI

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/GromacsWrapper#79]
Install
- [ ] Gromacs 5.1.x
- [ ] Gromacs 4.6.7
so that we can run a build matrix.

Needed to complete #39.

See Also: PR Becksteinlab/MDPOW#44 and issue Becksteinlab/MDPOW#41.

**Comment by orbeckst** [comment]
@ianmkenney please apply your magic from Becksteinlab/MDPOW#44 !

**Comment by orbeckst** [comment]
Once PR #69 is merged, we won't need a fancy cfg file anymore because tools will be autoloaded.

**Comment by ianmkenney** [comment]
Will do!

**Comment by pslacerda** [comment]
With tests in place we can go wild guaranteeing that it still works.

**Comment by orbeckst** [comment]
> On 2 Aug, 2016, at 18:57, Pedro Lacerda <notifications@github.com> wrote:
> 
> With tests in place we can go wild guaranteeing that it still works.

Yes, that's the idea. But first we need to clean up the existing tests and add a few new ones.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com
