### ISSUE TITLE
ITP #define expansion not supported 

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/GromacsWrapper#9]
The preprocessor does not recognize #define directives that define text such as 

```
 #define dih_chi1N   -0.76567   2.70705   4.02501  -5.96639   0.00000   0.00000 ; C*     CT     CT_2   N:  Chi-1 peptides AA
```

which defines the token _dih_chi1N_ that should be expanded in lines such as 

```
   14   12   15   17     3  dih_chi1H  ; chi1 dihedral, from PHE
```

It fails with

```
SyntaxError: File: "/..../test.itp", line 187
SyntaxError: Invalid #define directive
```

The preprocessor is very simplistic and only handles simple #ifdef/#ifndef decisions and not textual replacement.

**Comment by pslacerda** [comment]
Here we can use a real C preprocessor (cpp):

* clang or gcc preprocessors: http://stackoverflow.com/a/3917365/199332
* Python implementation: https://github.com/dabeaz/ply/blob/master/ply/cpp.py

I see these options:

* use current preprocessing only if gcc or clang isn't found
* use only cpp.py
* requires gcc or clang and use it

**Comment by orbeckst** [comment]
I am not sure if it's worth the effort to do the parsing. The fine folks at [ParmEd](https://github.com/ParmEd/ParmEd) have figured out most of it already. 

Some rudimentary ITP handling is useful but I think GW should concentrate more on the other aspects and perhaps file formats that are not well supported elsewhere.

I am just leaving this issue open so that if anyone ever wants to use the ITP parser then at least they see what the problems are.
